#!/bin/bash
img_path=$1
cd /app/debug
/app/install/paddle_lite_ocr/paddle_lite_ocr ch_ppocr_mobile_v2.0_det_slim_opt.nb ch_ppocr_mobile_v2.0_rec_slim_opt.nb ch_ppocr_mobile_v2.0_cls_slim_opt.nb  /data/$img_path ./ppocr_keys_v1.txt
